"""empty message

Revision ID: 075dd146dd06
Revises: c3d4e5f6a7b8
Create Date: 2026-04-30 15:09:29.842399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '075dd146dd06'
down_revision = 'c3d4e5f6a7b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
