"""your migration message

Revision ID: 1cdf2c149c33
Revises: b7c8d9e0f1a2
Create Date: 2026-05-04 17:46:25.780260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cdf2c149c33'
down_revision = 'b7c8d9e0f1a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_variants_fit_id'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_material_id'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_neck_type_id'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_pattern_id'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_sleeve_type_id'), table_name='product_variants')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_product_variants_sleeve_type_id'), 'product_variants', ['sleeve_type_id'], unique=False)
    op.create_index(op.f('ix_product_variants_pattern_id'), 'product_variants', ['pattern_id'], unique=False)
    op.create_index(op.f('ix_product_variants_neck_type_id'), 'product_variants', ['neck_type_id'], unique=False)
    op.create_index(op.f('ix_product_variants_material_id'), 'product_variants', ['material_id'], unique=False)
    op.create_index(op.f('ix_product_variants_fit_id'), 'product_variants', ['fit_id'], unique=False)
    # ### end Alembic commands ###
