"""empty message

Revision ID: 2881141dffd3
Revises: a1b2c3d4e5f6
Create Date: 2026-04-30 15:02:49.233321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2881141dffd3'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_category_price'), table_name='products')
    op.drop_index(op.f('ix_products_category_rating'), table_name='products')
    op.drop_index(op.f('ix_products_platform_category'), table_name='products')
    op.drop_index(op.f('ix_products_scraped_at'), table_name='products')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_products_scraped_at'), 'products', ['scraped_at'], unique=False)
    op.create_index(op.f('ix_products_platform_category'), 'products', ['platform', 'category'], unique=False)
    op.create_index(op.f('ix_products_category_rating'), 'products', ['category', 'rating'], unique=False)
    op.create_index(op.f('ix_products_category_price'), 'products', ['category', 'current_price'], unique=False)
    # ### end Alembic commands ###
