"""empty message

Revision ID: 374a50606fd4
Revises: f1a2b3c4d5e6
Create Date: 2026-05-04 13:35:18.003459

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '374a50606fd4'
down_revision = 'f1a2b3c4d5e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_products_brand'), table_name='products_legacy')
    op.drop_index(op.f('idx_products_category'), table_name='products_legacy')
    op.drop_index(op.f('idx_products_current_price'), table_name='products_legacy')
    op.drop_index(op.f('idx_products_platform'), table_name='products_legacy')
    op.drop_index(op.f('idx_products_rating'), table_name='products_legacy')
    op.drop_index(op.f('idx_products_scraped_at'), table_name='products_legacy')
    op.drop_table('products_legacy')
    op.drop_index(op.f('ix_nordstrom_womens_dresses_id'), table_name='nordstrom_womens_dresses')
    op.drop_table('nordstrom_womens_dresses')
    op.drop_index(op.f('idx_review_sig_captured_at'), table_name='review_signals')
    op.drop_index(op.f('idx_review_sig_rating'), table_name='review_signals')
    op.drop_index(op.f('idx_review_sig_sku_id'), table_name='review_signals')
    op.drop_table('review_signals')
    op.drop_table('genders')
    op.drop_table('schema_migrations')
    op.drop_index(op.f('ix_nordstrom_mens_tshirts_id'), table_name='nordstrom_mens_tshirts')
    op.drop_table('nordstrom_mens_tshirts')
    op.create_index(op.f('ix_brands_brand_id'), 'brands', ['brand_id'], unique=False)
    op.create_index(op.f('ix_categories_category_id'), 'categories', ['category_id'], unique=False)
    op.create_index(op.f('ix_colors_color_id'), 'colors', ['color_id'], unique=False)
    op.alter_column('platforms', 'display_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('platforms', 'base_url',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_index(op.f('ix_platforms_id'), 'platforms', ['id'], unique=False)
    op.drop_table_comment(
        'platforms',
        existing_comment='Lookup table for supported marketplace platforms.',
        schema=None
    )
    op.drop_column('platforms', 'created_at')
    op.alter_column('product_variants', 'currency',
               existing_type=sa.CHAR(length=3),
               type_=sa.String(length=3),
               existing_nullable=False,
               existing_server_default=sa.text("'USD'::bpchar"))
    op.alter_column('product_variants', 'scraped_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_pv_color_id'), table_name='product_variants')
    op.drop_index(op.f('idx_pv_price'), table_name='product_variants')
    op.drop_index(op.f('idx_pv_product_id'), table_name='product_variants')
    op.drop_index(op.f('idx_pv_scraped_at'), table_name='product_variants')
    op.drop_index(op.f('idx_pv_size_id'), table_name='product_variants')
    op.create_index(op.f('ix_product_variants_variant_id'), 'product_variants', ['variant_id'], unique=False)
    op.drop_constraint(op.f('product_variants_product_id_fkey'), 'product_variants', type_='foreignkey')
    op.create_foreign_key(None, 'product_variants', 'products', ['product_id'], ['product_id'])
    op.alter_column('products', 'scraped_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_products_brand_id'), table_name='products')
    op.drop_index(op.f('idx_products_category_id'), table_name='products')
    op.drop_index(op.f('idx_products_platform_id'), table_name='products')
    op.create_index(op.f('ix_products_product_id'), 'products', ['product_id'], unique=False)
    op.alter_column('recommendations', 'generated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_recommendations_category'), table_name='recommendations')
    op.drop_index(op.f('idx_recommendations_generated_at'), table_name='recommendations')
    op.drop_index(op.f('idx_recommendations_pattern_type'), table_name='recommendations')
    op.drop_index(op.f('idx_recommendations_status'), table_name='recommendations')
    op.create_index(op.f('ix_recommendations_rec_id'), 'recommendations', ['rec_id'], unique=False)
    op.alter_column('reviews', 'pros',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('reviews', 'cons',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('reviews', 'scraped_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_reviews_product_id'), table_name='reviews')
    op.drop_index(op.f('idx_reviews_scraped_at'), table_name='reviews')
    op.create_index(op.f('ix_reviews_review_id'), 'reviews', ['review_id'], unique=False)
    op.drop_constraint(op.f('reviews_product_id_fkey'), 'reviews', type_='foreignkey')
    op.create_foreign_key(None, 'reviews', 'products', ['product_id'], ['product_id'])
    op.create_index(op.f('ix_sizes_size_id'), 'sizes', ['size_id'], unique=False)
    op.alter_column('trend_scores', 'review_count',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('trend_scores', 'product_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('trend_scores', 'computed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_trend_scores_attr_key'), table_name='trend_scores')
    op.drop_index(op.f('idx_trend_scores_category'), table_name='trend_scores')
    op.drop_index(op.f('idx_trend_scores_momentum'), table_name='trend_scores')
    op.drop_index(op.f('idx_trend_scores_platform'), table_name='trend_scores')
    op.create_index(op.f('ix_trend_scores_score_id'), 'trend_scores', ['score_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trend_scores_score_id'), table_name='trend_scores')
    op.create_index(op.f('idx_trend_scores_platform'), 'trend_scores', ['platform'], unique=False)
    op.create_index(op.f('idx_trend_scores_momentum'), 'trend_scores', [sa.literal_column('momentum_score DESC')], unique=False)
    op.create_index(op.f('idx_trend_scores_category'), 'trend_scores', ['category'], unique=False)
    op.create_index(op.f('idx_trend_scores_attr_key'), 'trend_scores', ['attr_key'], unique=False)
    op.alter_column('trend_scores', 'computed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('trend_scores', 'product_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('trend_scores', 'review_count',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_sizes_size_id'), table_name='sizes')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_foreign_key(op.f('reviews_product_id_fkey'), 'reviews', 'products', ['product_id'], ['product_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_reviews_review_id'), table_name='reviews')
    op.create_index(op.f('idx_reviews_scraped_at'), 'reviews', ['scraped_at'], unique=False)
    op.create_index(op.f('idx_reviews_product_id'), 'reviews', ['product_id'], unique=False)
    op.alter_column('reviews', 'scraped_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('reviews', 'cons',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('reviews', 'pros',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_recommendations_rec_id'), table_name='recommendations')
    op.create_index(op.f('idx_recommendations_status'), 'recommendations', ['status'], unique=False)
    op.create_index(op.f('idx_recommendations_pattern_type'), 'recommendations', ['pattern_type'], unique=False)
    op.create_index(op.f('idx_recommendations_generated_at'), 'recommendations', [sa.literal_column('generated_at DESC')], unique=False)
    op.create_index(op.f('idx_recommendations_category'), 'recommendations', ['category'], unique=False)
    op.alter_column('recommendations', 'generated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_products_product_id'), table_name='products')
    op.create_index(op.f('idx_products_platform_id'), 'products', ['platform_id'], unique=False)
    op.create_index(op.f('idx_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index(op.f('idx_products_brand_id'), 'products', ['brand_id'], unique=False)
    op.alter_column('products', 'scraped_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'product_variants', type_='foreignkey')
    op.create_foreign_key(op.f('product_variants_product_id_fkey'), 'product_variants', 'products', ['product_id'], ['product_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_product_variants_variant_id'), table_name='product_variants')
    op.create_index(op.f('idx_pv_size_id'), 'product_variants', ['size_id'], unique=False)
    op.create_index(op.f('idx_pv_scraped_at'), 'product_variants', ['scraped_at'], unique=False)
    op.create_index(op.f('idx_pv_product_id'), 'product_variants', ['product_id'], unique=False)
    op.create_index(op.f('idx_pv_price'), 'product_variants', ['price'], unique=False)
    op.create_index(op.f('idx_pv_color_id'), 'product_variants', ['color_id'], unique=False)
    op.alter_column('product_variants', 'scraped_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('product_variants', 'currency',
               existing_type=sa.String(length=3),
               type_=sa.CHAR(length=3),
               existing_nullable=False,
               existing_server_default=sa.text("'USD'::bpchar"))
    op.add_column('platforms', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.create_table_comment(
        'platforms',
        'Lookup table for supported marketplace platforms.',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_platforms_id'), table_name='platforms')
    op.alter_column('platforms', 'base_url',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('platforms', 'display_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_index(op.f('ix_colors_color_id'), table_name='colors')
    op.drop_index(op.f('ix_categories_category_id'), table_name='categories')
    op.drop_index(op.f('ix_brands_brand_id'), table_name='brands')
    op.create_table('nordstrom_mens_tshirts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('platform', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('platform_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('brand', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('gender', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('sub_category', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('currency', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('current_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('original_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('discount_percent', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('rating', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=True),
    sa.Column('review_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('attributes_json', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('stock_variants_json', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('review_json', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('raw_json', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('data_label', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('poc_run_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('scraped_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('color', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('size', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('neck_type', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('fit', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('pattern', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('material', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('care_instructions', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sleeve_type', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('nordstrom_mens_tshirts_pkey')),
    sa.UniqueConstraint('url', name=op.f('nordstrom_mens_tshirts_url_key'))
    )
    op.create_index(op.f('ix_nordstrom_mens_tshirts_id'), 'nordstrom_mens_tshirts', ['id'], unique=False)
    op.create_table('schema_migrations',
    sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('applied_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('filename', name=op.f('schema_migrations_pkey'))
    )
    op.create_table('genders',
    sa.Column('id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('genders_pkey')),
    sa.UniqueConstraint('name', name=op.f('genders_name_key'))
    )
    op.create_table('review_signals',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sku_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=True),
    sa.Column('review_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('review_velocity_30d', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('sentiment_score', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('reviewer_region', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('review_details_json', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('captured_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('review_signals_pkey')),
    comment='Review count, rating, and velocity metrics per SKU per scrape cycle.'
    )
    op.create_index(op.f('idx_review_sig_sku_id'), 'review_signals', ['sku_id'], unique=False)
    op.create_index(op.f('idx_review_sig_rating'), 'review_signals', ['rating'], unique=False)
    op.create_index(op.f('idx_review_sig_captured_at'), 'review_signals', ['captured_at'], unique=False)
    op.create_table('nordstrom_womens_dresses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('platform', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('platform_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('brand', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('gender', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('sub_category', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('currency', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('current_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('original_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('discount_percent', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('rating', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=True),
    sa.Column('review_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('attributes_json', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('stock_variants_json', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('review_json', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('raw_json', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('data_label', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('poc_run_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('scraped_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('color', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('neck_type', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('dress_length', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('occasion', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('fit', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('pattern', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('closure_type', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('material', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('care_instructions', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sleeve_type', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('nordstrom_womens_dresses_pkey')),
    sa.UniqueConstraint('url', name=op.f('nordstrom_womens_dresses_url_key'))
    )
    op.create_index(op.f('ix_nordstrom_womens_dresses_id'), 'nordstrom_womens_dresses', ['id'], unique=False)
    op.create_table('products_legacy',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('platform', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('platform_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('brand', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('gender', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('sub_category', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('current_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('original_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('discount_percent', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('currency', sa.VARCHAR(length=10), server_default=sa.text("'USD'::character varying"), autoincrement=False, nullable=False),
    sa.Column('rating', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=True),
    sa.Column('review_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('attributes_json', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('stock_variants_json', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('review_json', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('raw_json', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('data_label', sa.VARCHAR(length=100), server_default=sa.text("'demonstration_data'::character varying"), autoincrement=False, nullable=True),
    sa.Column('poc_run_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('scraped_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('products_pkey')),
    sa.UniqueConstraint('url', name=op.f('products_url_key'))
    )
    op.create_index(op.f('idx_products_scraped_at'), 'products_legacy', ['scraped_at'], unique=False)
    op.create_index(op.f('idx_products_rating'), 'products_legacy', ['rating'], unique=False)
    op.create_index(op.f('idx_products_platform'), 'products_legacy', ['platform'], unique=False)
    op.create_index(op.f('idx_products_current_price'), 'products_legacy', ['current_price'], unique=False)
    op.create_index(op.f('idx_products_category'), 'products_legacy', ['category'], unique=False)
    op.create_index(op.f('idx_products_brand'), 'products_legacy', ['brand'], unique=False)
    # ### end Alembic commands ###
