"""empty message

Revision ID: 52929f8a42f0
Revises: 
Create Date: 2026-04-28 15:47:53.306360

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '52929f8a42f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nordstrom_mens_tshirts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('brand', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.String(length=30), nullable=False),
    sa.Column('sub_category', sa.String(length=150), nullable=True),
    sa.Column('current_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('discount_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('actual_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('original_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('price_text', sa.Text(), nullable=True),
    sa.Column('discount_text', sa.Text(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('color', sa.Text(), nullable=True),
    sa.Column('size', sa.Text(), nullable=True),
    sa.Column('stock_json', sa.Text(), nullable=True),
    sa.Column('pattern', sa.String(length=150), nullable=True),
    sa.Column('material', sa.Text(), nullable=True),
    sa.Column('neck_type', sa.String(length=150), nullable=True),
    sa.Column('sleeve_type', sa.String(length=150), nullable=True),
    sa.Column('fit', sa.String(length=150), nullable=True),
    sa.Column('dress_length', sa.String(length=150), nullable=True),
    sa.Column('occasion', sa.String(length=150), nullable=True),
    sa.Column('closure_type', sa.String(length=150), nullable=True),
    sa.Column('care_instructions', sa.Text(), nullable=True),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('review_fit', sa.Text(), nullable=True),
    sa.Column('star_distribution_json', sa.Text(), nullable=True),
    sa.Column('review_pros_json', sa.Text(), nullable=True),
    sa.Column('review_cons_json', sa.Text(), nullable=True),
    sa.Column('review_details_json', sa.Text(), nullable=True),
    sa.Column('raw_attributes_json', sa.Text(), nullable=True),
    sa.Column('data_label', sa.String(length=100), nullable=True),
    sa.Column('poc_run_id', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_nordstrom_mens_tshirts_id'), 'nordstrom_mens_tshirts', ['id'], unique=False)
    op.drop_index(op.f('ix_sku_listings_id'), table_name='sku_listings')
    op.drop_table('sku_listings')
    op.drop_index(op.f('ix_sku_attributes_id'), table_name='sku_attributes')
    op.drop_table('sku_attributes')
    op.drop_index(op.f('ix_review_signals_id'), table_name='review_signals')
    op.drop_table('review_signals')
    op.drop_index(op.f('ix_price_snapshots_id'), table_name='price_snapshots')
    op.drop_table('price_snapshots')
    op.drop_table('platforms')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platforms',
    sa.Column('id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('base_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('platforms_pkey')),
    sa.UniqueConstraint('name', name=op.f('platforms_name_key'))
    )
    op.create_table('price_snapshots',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sku_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('original_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('discount_percent', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('currency', sa.VARCHAR(length=10), server_default=sa.text("'USD'::character varying"), autoincrement=False, nullable=True),
    sa.Column('price_band', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('captured_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('price_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('discount_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['sku_id'], ['sku_listings.id'], name=op.f('price_snapshots_sku_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('price_snapshots_pkey'))
    )
    op.create_index(op.f('ix_price_snapshots_id'), 'price_snapshots', ['id'], unique=False)
    op.create_table('review_signals',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sku_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=True),
    sa.Column('review_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('review_velocity_30d', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('sentiment_score', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('reviewer_region', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('captured_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('review_details_json', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['sku_id'], ['sku_listings.id'], name=op.f('review_signals_sku_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('review_signals_pkey'))
    )
    op.create_index(op.f('ix_review_signals_id'), 'review_signals', ['id'], unique=False)
    op.create_table('sku_attributes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sku_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('size', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('color', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('pattern', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('material', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('neck_type', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('sleeve_type', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('fit', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('dress_length', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('occasion', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('closure_type', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('care_instructions', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('raw_attributes_json', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('stock_json', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['sku_id'], ['sku_listings.id'], name=op.f('sku_attributes_sku_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('sku_attributes_pkey')),
    sa.UniqueConstraint('sku_id', name=op.f('sku_attributes_sku_id_key'))
    )
    op.create_index(op.f('ix_sku_attributes_id'), 'sku_attributes', ['id'], unique=False)
    op.create_table('sku_listings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('platform_id', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('platform', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('brand', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('gender', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('sub_category', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('current_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('currency', sa.VARCHAR(length=10), server_default=sa.text("'USD'::character varying"), autoincrement=False, nullable=True),
    sa.Column('rating', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=True),
    sa.Column('review_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('data_label', sa.VARCHAR(length=100), server_default=sa.text("'demonstration_data'::character varying"), autoincrement=False, nullable=True),
    sa.Column('poc_run_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('scraped_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], name=op.f('sku_listings_platform_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('sku_listings_pkey')),
    sa.UniqueConstraint('url', name=op.f('sku_listings_url_key'))
    )
    op.create_index(op.f('ix_sku_listings_id'), 'sku_listings', ['id'], unique=False)
    op.drop_index(op.f('ix_nordstrom_mens_tshirts_id'), table_name='nordstrom_mens_tshirts')
    op.drop_table('nordstrom_mens_tshirts')
    # ### end Alembic commands ###
