"""empty message

Revision ID: 56439a7ee7e0
Revises: c8d9e0f1a2b3
Create Date: 2026-05-06 17:08:08.596043

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '56439a7ee7e0'
down_revision = 'c8d9e0f1a2b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_variants_created_at'), table_name='product_variants')
    op.add_column('products', sa.Column('image', sa.LargeBinary(), nullable=True))
    op.drop_index(op.f('ix_products_created_at'), table_name='products')
    op.add_column('reviews', sa.Column('comment_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index(op.f('ix_reviews_created_at'), table_name='reviews')
    op.alter_column('trend_scores', 'weeks_observed',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trend_scores', 'weeks_observed',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.create_index(op.f('ix_reviews_created_at'), 'reviews', ['created_at'], unique=False)
    op.drop_column('reviews', 'comment_json')
    op.create_index(op.f('ix_products_created_at'), 'products', ['created_at'], unique=False)
    op.drop_column('products', 'image')
    op.create_index(op.f('ix_product_variants_created_at'), 'product_variants', ['created_at'], unique=False)
    # ### end Alembic commands ###
