"""empty message

Revision ID: a5c22115ce6d
Revises: 52929f8a42f0
Create Date: 2026-04-28 15:50:41.800659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5c22115ce6d'
down_revision = '52929f8a42f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nordstrom_mens_tshirts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('brand', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.String(length=30), nullable=False),
    sa.Column('sub_category', sa.String(length=150), nullable=True),
    sa.Column('current_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('discount_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('actual_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('original_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('price_text', sa.Text(), nullable=True),
    sa.Column('discount_text', sa.Text(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('color', sa.Text(), nullable=True),
    sa.Column('size', sa.Text(), nullable=True),
    sa.Column('stock_json', sa.Text(), nullable=True),
    sa.Column('pattern', sa.String(length=150), nullable=True),
    sa.Column('material', sa.Text(), nullable=True),
    sa.Column('neck_type', sa.String(length=150), nullable=True),
    sa.Column('sleeve_type', sa.String(length=150), nullable=True),
    sa.Column('fit', sa.String(length=150), nullable=True),
    sa.Column('dress_length', sa.String(length=150), nullable=True),
    sa.Column('occasion', sa.String(length=150), nullable=True),
    sa.Column('closure_type', sa.String(length=150), nullable=True),
    sa.Column('care_instructions', sa.Text(), nullable=True),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('review_fit', sa.Text(), nullable=True),
    sa.Column('star_distribution_json', sa.Text(), nullable=True),
    sa.Column('review_pros_json', sa.Text(), nullable=True),
    sa.Column('review_cons_json', sa.Text(), nullable=True),
    sa.Column('review_details_json', sa.Text(), nullable=True),
    sa.Column('raw_attributes_json', sa.Text(), nullable=True),
    sa.Column('data_label', sa.String(length=100), nullable=True),
    sa.Column('poc_run_id', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_nordstrom_mens_tshirts_id'), 'nordstrom_mens_tshirts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nordstrom_mens_tshirts_id'), table_name='nordstrom_mens_tshirts')
    op.drop_table('nordstrom_mens_tshirts')
    # ### end Alembic commands ###
