"""empty message

Revision ID: e986b170af86
Revises: a5c22115ce6d
Create Date: 2026-04-29 13:59:59.673495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e986b170af86'
down_revision = 'a5c22115ce6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nordstrom_womens_dresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('brand', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.String(length=30), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('stock_price_json', sa.Text(), nullable=True),
    sa.Column('attributes_json', sa.Text(), nullable=True),
    sa.Column('review_json', sa.Text(), nullable=True),
    sa.Column('raw_product_json', sa.Text(), nullable=True),
    sa.Column('json_file_path', sa.Text(), nullable=True),
    sa.Column('data_label', sa.String(length=100), nullable=True),
    sa.Column('poc_run_id', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_nordstrom_womens_dresses_id'), 'nordstrom_womens_dresses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nordstrom_womens_dresses_id'), table_name='nordstrom_womens_dresses')
    op.drop_table('nordstrom_womens_dresses')
    # ### end Alembic commands ###
